### ISSUE TITLE
Prod build flow

### ISSUE THREAD

**Issue by saniko** [kaytrance/sails-react-webpack-starter-kit#1]
Hi,
Any production build is planned?

**Comment by kaytrance** [comment]
Yes, I am planning to add complete production flow. Right now production minifications can be done by editing `tasks/config/webpack.js` file and uncommenting uglification pluggin.

**Comment by kaytrance** [comment]
Done. See [#c4b6474](https://github.com/kaytrance/sails-react-webpack-starter-kit/commit/c4b6474defe9084c5090936f7fa14ca6009e170e)
